
- name: create project directory
  file: path={{ prjpath }}
        state=directory

- name: install epel
  yum: name=epel-release state=latest


- name: install nodejs
  yum: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm

- name: install npm package
  command: npm install webpack babel-core babel-loader babel-preset-es2015 expose-loader mofron chdir={{ prjpath }}

- name: copy config directory
  copy: src=./files/conf dest={{ prjpath }}

- name: create src directory
  copy: src=./files/src dest={{ prjpath }}

- name: copy index.html
  copy: src=index.html dest={{ prjpath }}

- name: create tool directory
  copy: src=./files/tool dest={{ prjpath }}

- name: copy ignore list
  copy: src=.gitignore dest={{ prjpath }}

